from typing import TypedDict

class ReviewState(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        username: The GitHub username to review.
        github_data: The data extracted from the GitHub API.
        feedback: The feedback generated by the code mentor.
    """
    username: str
    github_data: dict
    feedback: str